version: '2'
services:
    planningpoker-app:
        image: planningpoker
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://planningpoker-postgresql:5432/planningpoker
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    planningpoker-postgresql:
        extends:
            file: postgresql.yml
            service: planningpoker-postgresql
